language: python
python:
  - "3.6"
before_install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
install:
  - pip install .
script:
  - pytest -r  -v --cov-report=xml --cov=coconet tests/
after_success:
  - codecov
  
