language: python
python:
  - "3.6"
install:
  - pip install codecov
  - pip install .
script:
  - pytest --cov-report=xml tests/ --cov coconet
# Push the results to codecov
after_success:
  - codecov
  
