name: coconet
channels:
  - defaults
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python >=3.6
  - pyyaml
  - psutil
  - numpy
  - pandas >=1.0
  - h5py
  - scikit-learn
  - scipy
  - biopython
  - pytorch>=1.0
  - scikit-bio >=0.5.6
  - python-igraph >=0.8
  - pysam>=0.16
  - pybind11
  - pip
  - pip:
      - hnswlib

